# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.srcs/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC.xci
# IP: The module: 'PLL_ADC_DAC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.srcs/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC.xci
# IP: The module: 'PLL_ADC_DAC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/PLL_ADC_DAC/PLL_ADC_DAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_ADC_DAC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
