# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx/Project/200t/Fir_pass/Fir_pass.srcs/sources_1/ip/fir_compiler/fir_compiler.xci
# IP: The module: 'fir_compiler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/fir_compiler/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/fir_compiler/fir_compiler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Xilinx/Project/200t/Fir_pass/Fir_pass.srcs/sources_1/ip/fir_compiler/fir_compiler.xci
# IP: The module: 'fir_compiler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/fir_compiler/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/Fir_pass/Fir_pass.gen/sources_1/ip/fir_compiler/fir_compiler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
